[2025-08-18T03:23:01.595+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-08-18T03:23:01.626+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: update_stock_history.get.py scheduled__2025-08-18T03:22:00+00:00 [queued]>
[2025-08-18T03:23:01.637+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: update_stock_history.get.py scheduled__2025-08-18T03:22:00+00:00 [queued]>
[2025-08-18T03:23:01.637+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2025-08-18T03:23:01.651+0000] {taskinstance.py:2330} INFO - Executing <Task(BashOperator): get.py> on 2025-08-18 03:22:00+00:00
[2025-08-18T03:23:01.656+0000] {standard_task_runner.py:63} INFO - Started process 99489 to run task
[2025-08-18T03:23:01.661+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'update_stock_history', 'get.py', 'scheduled__2025-08-18T03:22:00+00:00', '--job-id', '8163', '--raw', '--subdir', 'DAGS_FOLDER/crawlchart/dags.py', '--cfg-path', '/tmp/tmpke4otdgc']
[2025-08-18T03:23:01.663+0000] {standard_task_runner.py:91} INFO - Job 8163: Subtask get.py
[2025-08-18T03:23:01.722+0000] {task_command.py:426} INFO - Running <TaskInstance: update_stock_history.get.py scheduled__2025-08-18T03:22:00+00:00 [running]> on host 1877907bc043
[2025-08-18T03:23:01.825+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='update_stock_history' AIRFLOW_CTX_TASK_ID='get.py' AIRFLOW_CTX_EXECUTION_DATE='2025-08-18T03:22:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-08-18T03:22:00+00:00'
[2025-08-18T03:23:01.826+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-08-18T03:23:01.841+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2025-08-18T03:23:01.842+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', "python3 '/www/server/***/dags/crawlchart/get.py'"]
[2025-08-18T03:23:01.858+0000] {subprocess.py:86} INFO - Output:
[2025-08-18T03:23:01.964+0000] {subprocess.py:93} INFO - python3: can't open file '/www/server/***/dags/crawlchart/get.py': [Errno 2] No such file or directory
[2025-08-18T03:23:01.968+0000] {subprocess.py:97} INFO - Command exited with return code 2
[2025-08-18T03:23:01.969+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-08-18T03:23:01.984+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/bash.py", line 243, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 2.
[2025-08-18T03:23:01.988+0000] {taskinstance.py:1206} INFO - Marking task as UP_FOR_RETRY. dag_id=update_stock_history, task_id=get.py, run_id=scheduled__2025-08-18T03:22:00+00:00, execution_date=20250818T032200, start_date=20250818T032301, end_date=20250818T032301
[2025-08-18T03:23:02.003+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 8163 for task get.py (Bash command failed. The command returned a non-zero exit code 2.; 99489)
[2025-08-18T03:23:02.032+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2025-08-18T03:23:02.063+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-08-18T03:23:02.065+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
