[2025-08-28T08:19:01.506+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-08-28T08:19:01.536+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: stock_details_dag.run_fetch_stock_details scheduled__2025-08-28T08:18:00+00:00 [queued]>
[2025-08-28T08:19:01.545+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: stock_details_dag.run_fetch_stock_details scheduled__2025-08-28T08:18:00+00:00 [queued]>
[2025-08-28T08:19:01.545+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2025-08-28T08:19:01.560+0000] {taskinstance.py:2330} INFO - Executing <Task(BashOperator): run_fetch_stock_details> on 2025-08-28 08:18:00+00:00
[2025-08-28T08:19:01.566+0000] {standard_task_runner.py:63} INFO - Started process 1663973 to run task
[2025-08-28T08:19:01.571+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'stock_details_dag', 'run_fetch_stock_details', 'scheduled__2025-08-28T08:18:00+00:00', '--job-id', '30703', '--raw', '--subdir', 'DAGS_FOLDER/stock_detail/dags.py', '--cfg-path', '/tmp/tmpx037zppo']
[2025-08-28T08:19:01.572+0000] {standard_task_runner.py:91} INFO - Job 30703: Subtask run_fetch_stock_details
[2025-08-28T08:19:01.629+0000] {task_command.py:426} INFO - Running <TaskInstance: stock_details_dag.run_fetch_stock_details scheduled__2025-08-28T08:18:00+00:00 [running]> on host 1877907bc043
[2025-08-28T08:19:01.734+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='stock_details_dag' AIRFLOW_CTX_TASK_ID='run_fetch_stock_details' AIRFLOW_CTX_EXECUTION_DATE='2025-08-28T08:18:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-08-28T08:18:00+00:00'
[2025-08-28T08:19:01.735+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-08-28T08:19:01.752+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2025-08-28T08:19:01.753+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'python /www/server/***/dags/stock_detail/stockdetail.py']
[2025-08-28T08:19:01.765+0000] {subprocess.py:86} INFO - Output:
[2025-08-28T08:19:01.862+0000] {subprocess.py:93} INFO - python: can't open file '/www/server/***/dags/stock_detail/stockdetail.py': [Errno 2] No such file or directory
[2025-08-28T08:19:01.865+0000] {subprocess.py:97} INFO - Command exited with return code 2
[2025-08-28T08:19:01.866+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-08-28T08:19:01.881+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/bash.py", line 243, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 2.
[2025-08-28T08:19:01.885+0000] {taskinstance.py:1206} INFO - Marking task as UP_FOR_RETRY. dag_id=stock_details_dag, task_id=run_fetch_stock_details, run_id=scheduled__2025-08-28T08:18:00+00:00, execution_date=20250828T081800, start_date=20250828T081901, end_date=20250828T081901
[2025-08-28T08:19:01.897+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 30703 for task run_fetch_stock_details (Bash command failed. The command returned a non-zero exit code 2.; 1663973)
[2025-08-28T08:19:01.943+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2025-08-28T08:19:01.974+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-08-28T08:19:01.976+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
[2025-08-28T08:19:47.973+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-08-28T08:19:48.021+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: stock_details_dag.run_fetch_stock_details scheduled__2025-08-28T08:18:00+00:00 [queued]>
[2025-08-28T08:19:48.036+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: stock_details_dag.run_fetch_stock_details scheduled__2025-08-28T08:18:00+00:00 [queued]>
[2025-08-28T08:19:48.036+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2025-08-28T08:19:48.055+0000] {taskinstance.py:2330} INFO - Executing <Task(BashOperator): run_fetch_stock_details> on 2025-08-28 08:18:00+00:00
[2025-08-28T08:19:48.063+0000] {standard_task_runner.py:63} INFO - Started process 1664137 to run task
[2025-08-28T08:19:48.069+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'stock_details_dag', 'run_fetch_stock_details', 'scheduled__2025-08-28T08:18:00+00:00', '--job-id', '30706', '--raw', '--subdir', 'DAGS_FOLDER/stock_detail/dags.py', '--cfg-path', '/tmp/tmprfrk23i4']
[2025-08-28T08:19:48.070+0000] {standard_task_runner.py:91} INFO - Job 30706: Subtask run_fetch_stock_details
[2025-08-28T08:19:48.127+0000] {task_command.py:426} INFO - Running <TaskInstance: stock_details_dag.run_fetch_stock_details scheduled__2025-08-28T08:18:00+00:00 [running]> on host 1877907bc043
[2025-08-28T08:19:48.222+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='stock_details_dag' AIRFLOW_CTX_TASK_ID='run_fetch_stock_details' AIRFLOW_CTX_EXECUTION_DATE='2025-08-28T08:18:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-08-28T08:18:00+00:00'
[2025-08-28T08:19:48.223+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-08-28T08:19:48.239+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2025-08-28T08:19:48.240+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'python /www/server/***/dags/stock_detail/stockdetail.py']
[2025-08-28T08:19:48.254+0000] {subprocess.py:86} INFO - Output:
[2025-08-28T08:19:48.358+0000] {subprocess.py:93} INFO - python: can't open file '/www/server/***/dags/stock_detail/stockdetail.py': [Errno 2] No such file or directory
[2025-08-28T08:19:48.363+0000] {subprocess.py:97} INFO - Command exited with return code 2
[2025-08-28T08:19:48.364+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-08-28T08:19:48.380+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/bash.py", line 243, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 2.
[2025-08-28T08:19:48.385+0000] {taskinstance.py:1206} INFO - Marking task as UP_FOR_RETRY. dag_id=stock_details_dag, task_id=run_fetch_stock_details, run_id=scheduled__2025-08-28T08:18:00+00:00, execution_date=20250828T081800, start_date=20250828T081948, end_date=20250828T081948
[2025-08-28T08:19:48.401+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 30706 for task run_fetch_stock_details (Bash command failed. The command returned a non-zero exit code 2.; 1664137)
[2025-08-28T08:19:48.441+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2025-08-28T08:19:48.472+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-08-28T08:19:48.474+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
