[2025-08-18T02:59:01.687+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-08-18T02:59:01.718+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: update_stock_history.get.py scheduled__2025-08-18T02:58:00+00:00 [queued]>
[2025-08-18T02:59:01.728+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: update_stock_history.get.py scheduled__2025-08-18T02:58:00+00:00 [queued]>
[2025-08-18T02:59:01.729+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2025-08-18T02:59:01.743+0000] {taskinstance.py:2330} INFO - Executing <Task(BashOperator): get.py> on 2025-08-18 02:58:00+00:00
[2025-08-18T02:59:01.749+0000] {standard_task_runner.py:63} INFO - Started process 97128 to run task
[2025-08-18T02:59:01.754+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'update_stock_history', 'get.py', 'scheduled__2025-08-18T02:58:00+00:00', '--job-id', '8062', '--raw', '--subdir', 'DAGS_FOLDER/crawlchart/dags.py', '--cfg-path', '/tmp/tmpkdvqx7b1']
[2025-08-18T02:59:01.755+0000] {standard_task_runner.py:91} INFO - Job 8062: Subtask get.py
[2025-08-18T02:59:01.809+0000] {task_command.py:426} INFO - Running <TaskInstance: update_stock_history.get.py scheduled__2025-08-18T02:58:00+00:00 [running]> on host 1877907bc043
[2025-08-18T02:59:01.929+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='update_stock_history' AIRFLOW_CTX_TASK_ID='get.py' AIRFLOW_CTX_EXECUTION_DATE='2025-08-18T02:58:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-08-18T02:58:00+00:00'
[2025-08-18T02:59:01.930+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-08-18T02:59:01.956+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2025-08-18T02:59:01.957+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', "python3 '/www/server/***/dags/crawlchart/get.py'"]
[2025-08-18T02:59:01.971+0000] {subprocess.py:86} INFO - Output:
[2025-08-18T02:59:02.076+0000] {subprocess.py:93} INFO - python3: can't open file '/www/server/***/dags/crawlchart/get.py': [Errno 2] No such file or directory
[2025-08-18T02:59:02.080+0000] {subprocess.py:97} INFO - Command exited with return code 2
[2025-08-18T02:59:02.081+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-08-18T02:59:02.099+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/bash.py", line 243, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 2.
[2025-08-18T02:59:02.104+0000] {taskinstance.py:1206} INFO - Marking task as UP_FOR_RETRY. dag_id=update_stock_history, task_id=get.py, run_id=scheduled__2025-08-18T02:58:00+00:00, execution_date=20250818T025800, start_date=20250818T025901, end_date=20250818T025902
[2025-08-18T02:59:02.122+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 8062 for task get.py (Bash command failed. The command returned a non-zero exit code 2.; 97128)
[2025-08-18T02:59:02.166+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2025-08-18T02:59:02.189+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-08-18T02:59:02.190+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
