[2025-09-08T08:00:01.237+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-09-08T08:00:01.266+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: update_stock_history.run_get_py scheduled__2025-09-08T07:59:00+00:00 [queued]>
[2025-09-08T08:00:01.276+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: update_stock_history.run_get_py scheduled__2025-09-08T07:59:00+00:00 [queued]>
[2025-09-08T08:00:01.276+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2025-09-08T08:00:01.291+0000] {taskinstance.py:2330} INFO - Executing <Task(BashOperator): run_get_py> on 2025-09-08 07:59:00+00:00
[2025-09-08T08:00:01.298+0000] {standard_task_runner.py:63} INFO - Started process 341593 to run task
[2025-09-08T08:00:01.302+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'update_stock_history', 'run_get_py', 'scheduled__2025-09-08T07:59:00+00:00', '--job-id', '161001', '--raw', '--subdir', 'DAGS_FOLDER/crawlchart/dags.py', '--cfg-path', '/tmp/tmp77sf2mg_']
[2025-09-08T08:00:01.303+0000] {standard_task_runner.py:91} INFO - Job 161001: Subtask run_get_py
[2025-09-08T08:00:01.360+0000] {task_command.py:426} INFO - Running <TaskInstance: update_stock_history.run_get_py scheduled__2025-09-08T07:59:00+00:00 [running]> on host 8d9cea3aac78
[2025-09-08T08:00:01.462+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='update_stock_history' AIRFLOW_CTX_TASK_ID='run_get_py' AIRFLOW_CTX_EXECUTION_DATE='2025-09-08T07:59:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-09-08T07:59:00+00:00'
[2025-09-08T08:00:01.463+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-09-08T08:00:01.487+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2025-09-08T08:00:01.489+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'python3 /opt/***/dags/crawlchart/get.py']
[2025-09-08T08:00:01.507+0000] {subprocess.py:86} INFO - Output:
[2025-09-08T08:00:02.130+0000] {subprocess.py:93} INFO - Traceback (most recent call last):
[2025-09-08T08:00:02.130+0000] {subprocess.py:93} INFO -   File "/opt/***/dags/crawlchart/get.py", line 2, in <module>
[2025-09-08T08:00:02.131+0000] {subprocess.py:93} INFO -     from VNSFintech import *
[2025-09-08T08:00:02.131+0000] {subprocess.py:93} INFO - ModuleNotFoundError: No module named 'VNSFintech'
[2025-09-08T08:00:02.161+0000] {subprocess.py:97} INFO - Command exited with return code 1
[2025-09-08T08:00:02.162+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-09-08T08:00:02.177+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/bash.py", line 243, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2025-09-08T08:00:02.182+0000] {taskinstance.py:1206} INFO - Marking task as UP_FOR_RETRY. dag_id=update_stock_history, task_id=run_get_py, run_id=scheduled__2025-09-08T07:59:00+00:00, execution_date=20250908T075900, start_date=20250908T080001, end_date=20250908T080002
[2025-09-08T08:00:02.200+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 161001 for task run_get_py (Bash command failed. The command returned a non-zero exit code 1.; 341593)
[2025-09-08T08:00:02.237+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2025-09-08T08:00:02.268+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-09-08T08:00:02.269+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
