[2025-09-01T18:00:02.751+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-09-01T18:00:02.780+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: market_table_foreign.activity_UPCOM scheduled__2025-09-01T17:59:00+00:00 [queued]>
[2025-09-01T18:00:02.790+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: market_table_foreign.activity_UPCOM scheduled__2025-09-01T17:59:00+00:00 [queued]>
[2025-09-01T18:00:02.790+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 11
[2025-09-01T18:00:02.806+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): activity_UPCOM> on 2025-09-01 17:59:00+00:00
[2025-09-01T18:00:02.816+0000] {standard_task_runner.py:63} INFO - Started process 2371934 to run task
[2025-09-01T18:00:02.821+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'market_table_foreign', 'activity_UPCOM', 'scheduled__2025-09-01T17:59:00+00:00', '--job-id', '46944', '--raw', '--subdir', 'DAGS_FOLDER/dag_market_live.py', '--cfg-path', '/tmp/tmpt1ag0y3v']
[2025-09-01T18:00:02.824+0000] {standard_task_runner.py:91} INFO - Job 46944: Subtask activity_UPCOM
[2025-09-01T18:00:02.893+0000] {task_command.py:426} INFO - Running <TaskInstance: market_table_foreign.activity_UPCOM scheduled__2025-09-01T17:59:00+00:00 [running]> on host 1877907bc043
[2025-09-01T18:00:02.990+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='market_table_foreign' AIRFLOW_CTX_TASK_ID='activity_UPCOM' AIRFLOW_CTX_EXECUTION_DATE='2025-09-01T17:59:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-09-01T17:59:00+00:00'
[2025-09-01T18:00:02.991+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-09-01T18:00:03.005+0000] {activity_UPCOM.py:17} INFO - Kết nối DB
[2025-09-01T18:00:03.177+0000] {activity_UPCOM.py:55} ERROR - Lỗi lưu activity_UPCOM
Traceback (most recent call last):
  File "/opt/airflow/dags/utils/market_data/activity_UPCOM.py", line 35, in activity_UPCOM
    point=float(dfindex.loc[dfindex['symbol']=='UpcomIndex','point'].values[0])
IndexError: index 0 is out of bounds for axis 0 with size 0
[2025-09-01T18:00:03.178+0000] {python.py:237} INFO - Done. Returned value was: None
[2025-09-01T18:00:03.179+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-09-01T18:00:03.190+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=market_table_foreign, task_id=activity_UPCOM, run_id=scheduled__2025-09-01T17:59:00+00:00, execution_date=20250901T175900, start_date=20250901T180002, end_date=20250901T180003
[2025-09-01T18:00:03.233+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2025-09-01T18:00:03.263+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-09-01T18:00:03.264+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
