[2025-09-05T08:57:01.975+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-09-05T08:57:02.002+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: activity.activity_HOSE scheduled__2025-09-05T08:56:00+00:00 [queued]>
[2025-09-05T08:57:02.012+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: activity.activity_HOSE scheduled__2025-09-05T08:56:00+00:00 [queued]>
[2025-09-05T08:57:02.012+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 11
[2025-09-05T08:57:02.025+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): activity_HOSE> on 2025-09-05 08:56:00+00:00
[2025-09-05T08:57:02.034+0000] {standard_task_runner.py:63} INFO - Started process 3167830 to run task
[2025-09-05T08:57:02.038+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'activity', 'activity_HOSE', 'scheduled__2025-09-05T08:56:00+00:00', '--job-id', '112779', '--raw', '--subdir', 'DAGS_FOLDER/dag_activity.py', '--cfg-path', '/tmp/tmpre5trhmm']
[2025-09-05T08:57:02.041+0000] {standard_task_runner.py:91} INFO - Job 112779: Subtask activity_HOSE
[2025-09-05T08:57:02.096+0000] {task_command.py:426} INFO - Running <TaskInstance: activity.activity_HOSE scheduled__2025-09-05T08:56:00+00:00 [running]> on host 1877907bc043
[2025-09-05T08:57:02.221+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='activity' AIRFLOW_CTX_TASK_ID='activity_HOSE' AIRFLOW_CTX_EXECUTION_DATE='2025-09-05T08:56:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-09-05T08:56:00+00:00'
[2025-09-05T08:57:02.223+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-09-05T08:57:02.239+0000] {activity_HOSE.py:17} INFO - Kết nối DB
[2025-09-05T08:57:02.297+0000] {activity_HOSE.py:55} ERROR - Lỗi lưu activity_HOSE
Traceback (most recent call last):
  File "/opt/airflow/dags/utils/market_data/activity/activity_HOSE.py", line 26, in activity_HOSE
    advancers_Val = hose[hose['matchChange'] > 0]['totalVal'].sum().astype(int)
AttributeError: 'int' object has no attribute 'astype'
[2025-09-05T08:57:02.298+0000] {python.py:237} INFO - Done. Returned value was: None
[2025-09-05T08:57:02.299+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-09-05T08:57:02.310+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=activity, task_id=activity_HOSE, run_id=scheduled__2025-09-05T08:56:00+00:00, execution_date=20250905T085600, start_date=20250905T085702, end_date=20250905T085702
[2025-09-05T08:57:02.370+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2025-09-05T08:57:02.387+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
