[2025-09-05T12:17:57.723+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-09-05T12:17:57.745+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: news_pipeline.add_postgre manual__2025-09-05T11:09:55.305363+00:00 [queued]>
[2025-09-05T12:17:57.752+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: news_pipeline.add_postgre manual__2025-09-05T11:09:55.305363+00:00 [queued]>
[2025-09-05T12:17:57.752+0000] {taskinstance.py:2306} INFO - Starting attempt 17 of 27
[2025-09-05T12:17:57.764+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): add_postgre> on 2025-09-05 11:09:55.305363+00:00
[2025-09-05T12:17:57.771+0000] {standard_task_runner.py:63} INFO - Started process 3206948 to run task
[2025-09-05T12:17:57.777+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'news_pipeline', 'add_postgre', 'manual__2025-09-05T11:09:55.305363+00:00', '--job-id', '115039', '--raw', '--subdir', 'DAGS_FOLDER/dag_news.py', '--cfg-path', '/tmp/tmpdfvxfqu1']
[2025-09-05T12:17:57.780+0000] {standard_task_runner.py:91} INFO - Job 115039: Subtask add_postgre
[2025-09-05T12:17:57.839+0000] {task_command.py:426} INFO - Running <TaskInstance: news_pipeline.add_postgre manual__2025-09-05T11:09:55.305363+00:00 [running]> on host 1877907bc043
[2025-09-05T12:17:57.922+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='news_pipeline' AIRFLOW_CTX_TASK_ID='add_postgre' AIRFLOW_CTX_EXECUTION_DATE='2025-09-05T11:09:55.305363+00:00' AIRFLOW_CTX_TRY_NUMBER='17' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-09-05T11:09:55.305363+00:00'
[2025-09-05T12:17:57.923+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-09-05T12:19:04.178+0000] {logging_mixin.py:188} INFO - ko thể click 5: Message: tab crashed
  (Session info: chrome=138.0.7204.183)
Stacktrace:
#0 0x563e907367da <unknown>
#1 0x563e901db133 <unknown>
#2 0x563e901c491e <unknown>
#3 0x563e901c3a4d <unknown>
#4 0x563e901c349a <unknown>
#5 0x563e901c3175 <unknown>
#6 0x563e901c0fd5 <unknown>
#7 0x563e901c192f <unknown>
#8 0x563e901d03e3 <unknown>
#9 0x563e901e983e <unknown>
#10 0x563e901f007b <unknown>
#11 0x563e901c2070 <unknown>
#12 0x563e901e8f83 <unknown>
#13 0x563e902785f6 <unknown>
#14 0x563e90252683 <unknown>
#15 0x563e9021eb5b <unknown>
#16 0x563e9021ff31 <unknown>
#17 0x563e906fb72b <unknown>
#18 0x563e906ff534 <unknown>
#19 0x563e906e2229 <unknown>
#20 0x563e907000d8 <unknown>
#21 0x563e906c661f <unknown>
#22 0x563e90723dd8 <unknown>
#23 0x563e90723fb6 <unknown>
#24 0x563e90735af6 <unknown>
#25 0x7ff36cefe134 <unknown>
[2025-09-05T12:19:04.192+0000] {add_postgre.py:46} ERROR - ❌ Lỗi trong add_postgres: Message: tab crashed
  (Session info: chrome=138.0.7204.183)
Stacktrace:
#0 0x563e907367da <unknown>
#1 0x563e901db133 <unknown>
#2 0x563e901c3125 <unknown>
#3 0x563e901c0fd5 <unknown>
#4 0x563e901c192f <unknown>
#5 0x563e901d03e3 <unknown>
#6 0x563e901e983e <unknown>
#7 0x563e901f007b <unknown>
#8 0x563e901c2070 <unknown>
#9 0x563e901e8f83 <unknown>
#10 0x563e902785f6 <unknown>
#11 0x563e90252683 <unknown>
#12 0x563e9021eb5b <unknown>
#13 0x563e9021ff31 <unknown>
#14 0x563e906fb72b <unknown>
#15 0x563e906ff534 <unknown>
#16 0x563e906e2229 <unknown>
#17 0x563e907000d8 <unknown>
#18 0x563e906c661f <unknown>
#19 0x563e90723dd8 <unknown>
#20 0x563e90723fb6 <unknown>
#21 0x563e90735af6 <unknown>
#22 0x7ff36cefe134 <unknown>

[2025-09-05T12:19:04.192+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-09-05T12:19:04.193+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/utils/new_pipeline/add_postgre.py", line 11, in add_postgres
    df=tintuc()
  File "/opt/airflow/dags/utils/new_pipeline/merge.py", line 9, in tintuc
    df3=cafef()
  File "/opt/airflow/dags/utils/new_pipeline/cafeF_ngay.py", line 52, in cafef
    soup=BeautifulSoup(driver.page_source,'html.parser')
  File "/home/airflow/.local/lib/python3.10/site-packages/selenium/webdriver/remote/webdriver.py", line 593, in page_source
    return self.execute(Command.GET_PAGE_SOURCE)["value"]
  File "/home/airflow/.local/lib/python3.10/site-packages/selenium/webdriver/remote/webdriver.py", line 454, in execute
    self.error_handler.check_response(response)
  File "/home/airflow/.local/lib/python3.10/site-packages/selenium/webdriver/remote/errorhandler.py", line 232, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: tab crashed
  (Session info: chrome=138.0.7204.183)
Stacktrace:
#0 0x563e907367da <unknown>
#1 0x563e901db133 <unknown>
#2 0x563e901c3125 <unknown>
#3 0x563e901c0fd5 <unknown>
#4 0x563e901c192f <unknown>
#5 0x563e901d03e3 <unknown>
#6 0x563e901e983e <unknown>
#7 0x563e901f007b <unknown>
#8 0x563e901c2070 <unknown>
#9 0x563e901e8f83 <unknown>
#10 0x563e902785f6 <unknown>
#11 0x563e90252683 <unknown>
#12 0x563e9021eb5b <unknown>
#13 0x563e9021ff31 <unknown>
#14 0x563e906fb72b <unknown>
#15 0x563e906ff534 <unknown>
#16 0x563e906e2229 <unknown>
#17 0x563e907000d8 <unknown>
#18 0x563e906c661f <unknown>
#19 0x563e90723dd8 <unknown>
#20 0x563e90723fb6 <unknown>
#21 0x563e90735af6 <unknown>
#22 0x7ff36cefe134 <unknown>

[2025-09-05T12:19:04.208+0000] {taskinstance.py:1206} INFO - Marking task as UP_FOR_RETRY. dag_id=news_pipeline, task_id=add_postgre, run_id=manual__2025-09-05T11:09:55.305363+00:00, execution_date=20250905T110955, start_date=20250905T121757, end_date=20250905T121904
[2025-09-05T12:19:04.222+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 115039 for task add_postgre (Message: tab crashed
  (Session info: chrome=138.0.7204.183)
Stacktrace:
#0 0x563e907367da <unknown>
#1 0x563e901db133 <unknown>
#2 0x563e901c3125 <unknown>
#3 0x563e901c0fd5 <unknown>
#4 0x563e901c192f <unknown>
#5 0x563e901d03e3 <unknown>
#6 0x563e901e983e <unknown>
#7 0x563e901f007b <unknown>
#8 0x563e901c2070 <unknown>
#9 0x563e901e8f83 <unknown>
#10 0x563e902785f6 <unknown>
#11 0x563e90252683 <unknown>
#12 0x563e9021eb5b <unknown>
#13 0x563e9021ff31 <unknown>
#14 0x563e906fb72b <unknown>
#15 0x563e906ff534 <unknown>
#16 0x563e906e2229 <unknown>
#17 0x563e907000d8 <unknown>
#18 0x563e906c661f <unknown>
#19 0x563e90723dd8 <unknown>
#20 0x563e90723fb6 <unknown>
#21 0x563e90735af6 <unknown>
#22 0x7ff36cefe134 <unknown>
; 3206948)
[2025-09-05T12:19:04.257+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2025-09-05T12:19:04.282+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-09-05T12:19:04.282+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
